apiVersion: v1
kind: ServiceAccount
metadata:
  name: stock-agent
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: stock-agent
    app: stock-agent
