apiVersion: v1
kind: Service
metadata:
  name: stock-server-mcp
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentgateway-demo
    agentgateway.dev/feature: stock-server-mcp
    app: stock-server-mcp
spec:
  selector:
    app: stock-server-mcp
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
